name: Cloud Functions

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  ENV_FILE: env.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: npm install -g pnpm
      - run: pnpm i --frozen-lockfile

      - run: tsc --project tsconfig.build.json
      
      - run: pnpm prune --prod

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > ${{ env.ENV_FILE }}

      - run: |
          cp package.json dist/package.json
          cp pnpm-lock.yaml dist/pnpm-lock.yaml

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA }}
      - run: cat ${{ env.ENV_FILE }}

      - id: deploy
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: ${{github.repository.name}}-${{ github.ref_name }}
          runtime: 'nodejs18'
          entry_point: main
          source_dir: dist
          region: us-central1
          timeout: 360
          memory_mb: 512MB
          https_trigger_security_level: security_level_unspecified
          env_vars_file: ${{ env.ENV_FILE }}
          service_account_email: ${{ secrets.GCP_SA }}
